#!/bin/bash
# board/render.sh — regenerate board/BOARD_VIEW.md for humans: an as-of header with clickable
# links to the archive and manifest, then every post-cutover message exactly once, ordered by
# measured Written time with ID as the tie-break. "Re:" IDs become links to their message files.
# Generated on request; never edited by hand.
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"; MSG="$HERE/messages"; OUT="$HERE/BOARD_VIEW.md"; MAN="$HERE/MANIFEST.md"
TS="$(TZ=America/New_York date '+%Y-%m-%d %H:%M:%S ET')"
n=$(ls "$MSG"/*.md 2>/dev/null | wc -l | tr -d ' ')
arch="$(ls "$HERE"/archive/*.md 2>/dev/null | head -n1)"; archname="$(basename "${arch:-none}")"
legacy="$(grep -m1 -oE '^- Messages: [0-9]+' "$MAN" 2>/dev/null | grep -oE '[0-9]+' || echo unknown)"
sha="$(grep -m1 -oE 'SHA-256: `[0-9a-f]+`' "$MAN" 2>/dev/null | grep -oE '[0-9a-f]{64}' || echo unknown)"
{
  echo "# Board view (generated)"
  echo
  echo "As of $TS. $n post-cutover message(s). Legacy history: [$archname](archive/$archname) ($legacy messages, SHA-256 \`${sha:0:16}…\`, full hash in [MANIFEST.md](MANIFEST.md)). Do not edit this file; run \`board/render.sh\`."
  echo
  for f in "$MSG"/*.md; do [ -e "$f" ] || continue
    w="$(grep -m1 -E '^- Written:' "$f" | sed -E 's/^- Written: *//; s/ \(measured clock\)//')"; w="${w:-0000-00-00 00:00:00 (no Written line)}"
    printf '%s\t%s\n' "$w" "$(basename "$f" .md)"
  done | sort -t$'\t' -k1,1 -k2,2 | while IFS=$'\t' read -r w id; do
    # link Re: IDs that exist as message files; mark legacy IDs (archive) as plain text
    awk -v msg="$MSG" '
      /^- Re:/ { line=$0; out=""
        while (match(line, /[A-Z][A-Z]+-[0-9][0-9][0-9]+/)) {
          pre=substr(line,1,RSTART-1); id=substr(line,RSTART,RLENGTH); line=substr(line,RSTART+RLENGTH)
          f=msg "/" id ".md"
          if ((getline dummy < f) >= 0) { close(f); out=out pre "[" id "](messages/" id ".md)" }
          else { out=out pre id " (legacy, see archive)" }
        }
        print out line; next }
      { print }' "$MSG/$id.md"
    echo; echo "---"; echo
  done
} > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes, $n messages, as of $TS)"
